### ISSUE TITLE
Fix Quail GUI TCP Intermittent connections

### ISSUE THREAD

**Issue by Timvrakas** [stanford-ssi/SpaceSalmon#43]
UDP seems reliable, but for sending commands there's some kind of issue. A few ideas:
- have constant pings and responses over TCP to make sure it stays active
- Auto-reconnect if there are any issues

**Comment by mikh3x4** [comment]
What does some kind of issue mean? Like they don’t go through randomly or it breaks and needs a servers restart? 

It’s a known issue that a quail restart requires a sever restart too

**Comment by Timvrakas** [comment]
We needed to restart the server several times before it would properly send commands. It was a significant process of needing play with everything before we got it working. But I think it's the same issue you're describing.

**Comment by mikh3x4** [comment]
Yeah currently there is no reconnection mechanism at all. I've been planing to write one as apart of a general clean up. I'll try to prioritize that

**Comment by mikh3x4** [comment]
Much improved with heartbeats and separate async computing for taking care of the tcp connection
