### ISSUE TITLE
Fix Ethernet Async MAC race condition for fragmented packets.

### ISSUE THREAD

**Issue by Timvrakas** [stanford-ssi/SpaceSalmon#44]
Sending multiple packets quickly causes later ones to get dropped. I fixed this is a recent commit by adding a vTaskDelay in the MAC handler to slow things down. I suspect the issue may be the MAC handlers async implementation.

**Comment by mikh3x4** [comment]
Is this fixed? I think it might be fixed with the MTU fragmenting

**Comment by Timvrakas** [comment]
I'm not sure. I can try to look at the commit log.

**Comment by Timvrakas** [comment]
No, it's still fixed with a very hacky hack [here](https://github.com/stanford-ssi/SpaceSalmon/blob/0a390ca1d52d581e61780819524ccf018a4d9765/lib/SSIEth/src/ethif_mac.cpp#L103).

**Comment by Timvrakas** [comment]
Ok here: https://github.com/stanford-ssi/SpaceSalmon/commit/c94c3b884da8af232831f626da39e89c9a694717
What I think was up:
LWIP understands how to used chained buffer descriptors, and the Ethernet MAC hardware also understands how to use chained buffer descriptors, but the dumb Atmel code in the middle does not. It should be killed with fire. But anyway what was happening is full-size frames (1518 bytes) were being split into two descriptors (1500 and 18 bytes, respectively) and then the descriptor buffer (only 2 deep for some reason?) didn't have enough room when the second frame came around.

@theDarkKnight5050 if you get a chance could you do an A/B test with these changes, and send some big packets and see if they get through?

**Comment by theDarkKnight5050** [comment]
Aye aye cap

From: Tim Vrakas ***@***.***>
Date: Friday, July 29, 2022 at 1:39 AM
To: stanford-ssi/SpaceSalmon ***@***.***>
Cc: Ahmed Ibrahim Abdalla ***@***.***>, Mention ***@***.***>
Subject: Re: [stanford-ssi/SpaceSalmon] Fix Ethernet Async MAC race condition for fragmented packets. (Issue #44)

Ok here: c94c3b8<https://github.com/stanford-ssi/SpaceSalmon/commit/c94c3b884da8af232831f626da39e89c9a694717>
What I think was up:
LWIP understands how to used chained buffer descriptors, and the Ethernet MAC hardware also understands how to use chained buffer descriptors, but the dumb Atmel code in the middle does not. It should be killed with fire. But anyway what was happening is full-size frames (1518 bytes) were being split into two descriptors (1500 and 18 bytes, respectively) and then the descriptor buffer (only 2 deep for some reason?) didn't have enough room when the second frame came around.

@theDarkKnight5050<https://github.com/theDarkKnight5050> if you get a chance could you do an A/B test with these changes, and send some big packets and see if they get through?

**Comment by Timvrakas** [comment]
This was fixed by #55, we now have legit DMA ethernet driver.
